apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sandbox
  namespace: sandbox-test
spec:
  rules:
    - host: sandbox.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sandbox
                port:
                  number: 80
